# docker-compose.yml
version: '3.8'

services:
  # PHP & Apache Servisi
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carteks-laravel-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "8087:80"
    depends_on:
      - db
    networks:
      - carteks-network

  # MySQL Veritabanı Servisi
  db:
    image: mysql:8.0
    platform: linux/arm64/v8 # M1/M2 için platform belirtiyoruz
    container_name: carteks-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - carteks-network

  # phpMyAdmin Servisi
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carteks-phpmyadmin
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - carteks-network

networks:
  carteks-network:
    driver: bridge

volumes:
  db_data:
    driver: local
